Add header component
crypto-pepe/p2p-marketplace pull request #5
Opened 2022-04-28 08:58 UTC by turbo-stump

2022-04-28 12:44 UTC, stuffy-idler commented on src/lib/header/navbar/Navbar.svelte
> +			{:else if link.href !== '/account' && link.href !== '/exchanges'}
I propose to filter `navLinks` at `<script>` section – it's better to separate UI and custom logic.

2022-04-28 12:45 UTC, stuffy-idler commented on src/lib/header/navbar/Navbar.svelte
> +	export let navLinks: {
You reuse this type (link) everywhere – let's define it at one place and reuse where it needed.

2022-04-28 12:47 UTC, stuffy-idler commented on tests/header.test.ts
> +	expect(await links).toEqual(expect.arrayContaining(requiredLinks));
Let's move `await` from `expect` to `links` initializing.

2022-04-28 12:49 UTC, stuffy-idler commented on src/lib/header/Header.svelte
> +	<div class="header__button">
Should it be visible only in case when user is not connected?

2022-04-29 07:30 UTC, turbo-stump commented on tests/header.test.ts
> +	expect(await links).toEqual(expect.arrayContaining(requiredLinks));
done

2022-04-29 07:56 UTC, turbo-stump commented on src/lib/header/Header.svelte
> +	<div class="header__button">
Do you mean header component?
Header component should be visible constantly.
isConnected prop used here for make visible Account and Exchanges links in navbar when user is connected

2022-04-29 08:34 UTC, turbo-stump commented on src/lib/header/navbar/Navbar.svelte
> +			{:else if link.href !== '/account' && link.href !== '/exchanges'}
Maybe this logic to place in upper level in header component? Cause navbar just showing links

2022-04-29 08:35 UTC, turbo-stump commented on src/lib/header/navbar/Navbar.svelte
> +			{:else if link.href !== '/account' && link.href !== '/exchanges'}
I made it in last commit

2022-04-29 08:49 UTC, turbo-stump commented on src/lib/header/Header.svelte
> +	<div class="header__button">
fixed earlier

2022-04-29 10:42 UTC, stupid-boar requested changes

2022-04-29 10:42 UTC, stupid-boar commented on src/lib/header/Header.svelte
> +	const getVisibleLinks = (): Link[] => {
=> navLinks.filter ..... (without return)

2022-04-29 10:42 UTC, stupid-boar commented on src/lib/header/navbar/Navbar.svelte
> +	import type { Link } from 'src/types/types';
types/types?

2022-04-29 10:42 UTC, stupid-boar commented on src/routes/account.svelte
> +	<title>Account</title>
P2P - Account

2022-04-29 10:42 UTC, stupid-boar commented on src/routes/exchanges.svelte
> +	<title>Exchanges</title>
P2P - Exchanges

2022-04-29 10:42 UTC, stupid-boar commented on src/routes/exchanges.svelte
> +</style>
newline

2022-04-29 10:42 UTC, stupid-boar commented on src/routes/index.svelte
> +	<title>pepe 2 pepe</title>
P2P - Marketplace

2022-04-29 10:42 UTC, stupid-boar commented on src/routes/stats.svelte
> +	<title>Stats</title>
P2P - Stats

2022-04-29 10:42 UTC, stupid-boar commented on src/types/types.ts
> +}
newline

2022-04-29 10:42 UTC, stupid-boar commented on tests/header.test.ts
> +})
newline

2022-04-29 10:43 UTC, turbo-stump commented on src/lib/header/Header.svelte
> +	const getVisibleLinks = (): Link[] => {
done

2022-04-29 10:52 UTC, turbo-stump commented on src/lib/header/navbar/Navbar.svelte
> +	import type { Link } from 'src/types/types';
moved types.ts to src

2022-04-29 10:52 UTC, turbo-stump commented on src/routes/account.svelte
> +	<title>Account</title>
done

2022-04-29 10:52 UTC, turbo-stump commented on src/routes/exchanges.svelte
> +	<title>Exchanges</title>
done

2022-04-29 10:53 UTC, turbo-stump commented on src/routes/exchanges.svelte
> +</style>
done

2022-04-29 10:53 UTC, turbo-stump commented on src/types/types.ts
> +}
done

2022-04-29 10:53 UTC, turbo-stump commented on tests/header.test.ts
> +})
done

2022-04-29 10:54 UTC, turbo-stump commented on src/routes/index.svelte
> +	<title>pepe 2 pepe</title>
done

2022-04-29 10:54 UTC, turbo-stump commented on src/routes/stats.svelte
> +	<title>Stats</title>
done

2022-04-29 10:57 UTC, stupid-boar submitted a review, later dismissed

2022-04-29 14:01 UTC, stuffy-idler commented on src/lib/header/Header.svelte
> +	<div class="header__button">
No, the question was about button "Connect" – when the user is already connected, this button is excess.

2022-04-29 14:48 UTC, stuffy-idler requested changes

2022-04-29 14:48 UTC, stuffy-idler commented on src/types.ts
> +  title?: string;
What is the difference between `content` and `title`? Can it be merged to single field?

2022-04-29 15:20 UTC, turbo-stump commented on src/types.ts
> +  title?: string;
link type fixed

2022-04-29 15:24 UTC, stuffy-idler approved these changes

2022-05-04 07:26 UTC, merged